import { cert, initializeApp } from 'firebase-admin/app';
import { getFirestore } from 'firebase-admin/firestore';
import { readFile } from 'node:fs/promises';

const serviceAccountPath = process.env.FIREBASE_SERVICE_ACCOUNT_PATH;
if (!serviceAccountPath) {
  throw new Error('Missing FIREBASE_SERVICE_ACCOUNT_PATH. Point it to your Firebase service account JSON.');
}

const rawServiceAccount = await readFile(serviceAccountPath, 'utf8');
const serviceAccount = JSON.parse(rawServiceAccount);
const projectId = process.env.FIREBASE_PROJECT_ID || serviceAccount.project_id;
if (!projectId) {
  throw new Error('Missing FIREBASE_PROJECT_ID and project_id in service account JSON.');
}

initializeApp({
  credential: cert(serviceAccount),
  projectId,
});

const db = getFirestore();
const now = new Date();

const users = [
  { id: 'seed-admin', displayName: 'ToneForge Seed', photoURL: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ToneForgeSeed', role: 'admin', createdAt: now, updatedAt: now },
];

const songs = [
  {
    id: 'song_song_gio',
    title: 'Sóng Gió',
    artist: 'Jack & K-ICM',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a1a2a5ee11d4?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=q3y7b4L0IhA',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 21000,
    difficulty: 'Easy',
    difficultyInfo: { label: 'Easy', colorClass: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' },
    pitchMetrics: { minPitch: 57, maxPitch: 72, modePitch: 64 },
    createdAt: now,
    updatedAt: now,
    viewCount: 21000,
    playCount: 21000,
    totalPracticeTime: 0,
    maxScore: 99,
  },
  {
    id: 'song_chac_ai_do_se_ve',
    title: 'Chắc Ai Đó Sẽ Về',
    artist: 'Sơn Tùng M-TP',
    genre: 'Ballad',
    thumbnail: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=5e2yGQYt7qE',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 12400,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 55, maxPitch: 74, modePitch: 63 },
    createdAt: now,
    updatedAt: now,
    viewCount: 12400,
    playCount: 12400,
    totalPracticeTime: 0,
    maxScore: 98,
  },
  {
    id: 'song_nang_tho',
    title: 'Nàng Thơ',
    artist: 'Hoàng Dũng',
    genre: 'Ballad',
    thumbnail: 'https://images.unsplash.com/photo-1507838153414-b4b713384a76?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=R4o2x2fL8qA',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 8900,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 53, maxPitch: 77, modePitch: 66 },
    createdAt: now,
    updatedAt: now,
    viewCount: 8900,
    playCount: 8900,
    totalPracticeTime: 0,
    maxScore: 95,
  },
  {
    id: 'song_vung_ky_uc',
    title: 'Vùng Ký Ức',
    artist: 'Chillies',
    genre: 'Indie',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=3yQ5u7rM6uM',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 5600,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 56, maxPitch: 75, modePitch: 64 },
    createdAt: now,
    updatedAt: now,
    viewCount: 5600,
    playCount: 5600,
    totalPracticeTime: 0,
    maxScore: 92,
  },
  {
    id: 'song_em_dao_nay',
    title: 'Em Dạo Này',
    artist: 'Ngọt',
    genre: 'Indie',
    thumbnail: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=U7M7J1eQ2tI',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 4200,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 54, maxPitch: 73, modePitch: 62 },
    createdAt: now,
    updatedAt: now,
    viewCount: 4200,
    playCount: 4200,
    totalPracticeTime: 0,
    maxScore: 91,
  },
  {
    id: 'song_duyen_phan',
    title: 'Duyên Phận',
    artist: 'Như Quỳnh',
    genre: 'Bolero',
    thumbnail: 'https://images.unsplash.com/photo-1525362081669-2b476bb628c3?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=0m2wT9mOQb4',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 15600,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 50, maxPitch: 71, modePitch: 59 },
    createdAt: now,
    updatedAt: now,
    viewCount: 15600,
    playCount: 15600,
    totalPracticeTime: 0,
    maxScore: 96,
  },
  {
    id: 'song_anh_nang_cua_anh',
    title: 'Ánh Nắng Của Anh',
    artist: 'Đức Phúc',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=QZpS5Wg5V4c',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 18450,
    difficulty: 'Easy',
    difficultyInfo: { label: 'Easy', colorClass: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' },
    pitchMetrics: { minPitch: 56, maxPitch: 75, modePitch: 65 },
    createdAt: now,
    updatedAt: now,
    viewCount: 18450,
    playCount: 18450,
    totalPracticeTime: 0,
    maxScore: 97,
  },
  {
    id: 'song_sau_tat_ca',
    title: 'Sau Tất Cả',
    artist: 'Erik',
    genre: 'Ballad',
    thumbnail: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=6r8rY9oY4f0',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 17120,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 54, maxPitch: 73, modePitch: 63 },
    createdAt: now,
    updatedAt: now,
    viewCount: 17120,
    playCount: 17120,
    totalPracticeTime: 0,
    maxScore: 96,
  },
  {
    id: 'song_dem_thay_ta',
    title: 'Đêm Thấy Ta Là Thác Đổ',
    artist: 'Ngọc Lan',
    genre: 'Bolero',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a1a2a5ee11d4?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=V2m0J3WQxZQ',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 14100,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 49, maxPitch: 70, modePitch: 58 },
    createdAt: now,
    updatedAt: now,
    viewCount: 14100,
    playCount: 14100,
    totalPracticeTime: 0,
    maxScore: 95,
  },
  {
    id: 'song_mua_ha_cuoi',
    title: 'Mùa Hạ Cuối',
    artist: 'Phan Mạnh Quỳnh',
    genre: 'Indie',
    thumbnail: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=R7Y4g2dYz7Q',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 10350,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 55, maxPitch: 74, modePitch: 64 },
    createdAt: now,
    updatedAt: now,
    viewCount: 10350,
    playCount: 10350,
    totalPracticeTime: 0,
    maxScore: 93,
  },
  {
    id: 'song_ve_que',
    title: 'Về Quê',
    artist: 'Đen',
    genre: 'Khac',
    thumbnail: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=6O8uM0X5YlQ',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 9800,
    difficulty: 'Easy',
    difficultyInfo: { label: 'Easy', colorClass: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' },
    pitchMetrics: { minPitch: 52, maxPitch: 69, modePitch: 61 },
    createdAt: now,
    updatedAt: now,
    viewCount: 9800,
    playCount: 9800,
    totalPracticeTime: 0,
    maxScore: 90,
  },
  {
    id: 'song_yeu_5',
    title: 'Yêu 5',
    artist: 'Rhymastic',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=5Jj2Z2xQ0kY',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 7600,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 57, maxPitch: 79, modePitch: 67 },
    createdAt: now,
    updatedAt: now,
    viewCount: 7600,
    playCount: 7600,
    totalPracticeTime: 0,
    maxScore: 94,
  },
  {
    id: 'song_buoc_qua_mua_co_don',
    title: 'Bước Qua Mùa Cô Đơn',
    artist: 'Vũ.',
    genre: 'Indie',
    thumbnail: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=YQGdM6xZ5v0',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 13240,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 54, maxPitch: 76, modePitch: 65 },
    createdAt: now,
    updatedAt: now,
    viewCount: 13240,
    playCount: 13240,
    totalPracticeTime: 0,
    maxScore: 94,
  },
  {
    id: 'song_can',
    title: 'Cần',
    artist: 'Tlinh',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1487180144351-b8472da7d491?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=8cQv7f0O4vQ',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 11780,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 58, maxPitch: 80, modePitch: 68 },
    createdAt: now,
    updatedAt: now,
    viewCount: 11780,
    playCount: 11780,
    totalPracticeTime: 0,
    maxScore: 93,
  },
  {
    id: 'song_trong_com_mua',
    title: 'Trong Cơn Mưa',
    artist: 'Da LAB',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=1VJ8D8p9z8E',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 10930,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 55, maxPitch: 74, modePitch: 63 },
    createdAt: now,
    updatedAt: now,
    viewCount: 10930,
    playCount: 10930,
    totalPracticeTime: 0,
    maxScore: 92,
  },
  {
    id: 'song_nho_anh',
    title: 'Nhớ Anh',
    artist: 'Min',
    genre: 'Ballad',
    thumbnail: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=0Z7G7f7NnQk',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 8650,
    difficulty: 'Easy',
    difficultyInfo: { label: 'Easy', colorClass: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' },
    pitchMetrics: { minPitch: 53, maxPitch: 71, modePitch: 61 },
    createdAt: now,
    updatedAt: now,
    viewCount: 8650,
    playCount: 8650,
    totalPracticeTime: 0,
    maxScore: 90,
  },
  {
    id: 'song_thang_tu_la_loi_noi_doi_cua_em',
    title: 'Tháng Tư Là Lời Nói Dối Của Em',
    artist: 'Hà Anh Tuấn',
    genre: 'Ballad',
    thumbnail: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=9Ff6dN6p7aQ',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 19220,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 52, maxPitch: 78, modePitch: 66 },
    createdAt: now,
    updatedAt: now,
    viewCount: 19220,
    playCount: 19220,
    totalPracticeTime: 0,
    maxScore: 98,
  },
  {
    id: 'song_bay_tren_canh_dieu',
    title: 'Bay Trên Cánh Diều',
    artist: 'Bích Phương',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=3FzV9x5mZ2Q',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 7100,
    difficulty: 'Easy',
    difficultyInfo: { label: 'Easy', colorClass: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' },
    pitchMetrics: { minPitch: 54, maxPitch: 72, modePitch: 62 },
    createdAt: now,
    updatedAt: now,
    viewCount: 7100,
    playCount: 7100,
    totalPracticeTime: 0,
    maxScore: 89,
  },
  {
    id: 'song_yeu_lam',
    title: 'Yêu Lắm',
    artist: 'JustaTee',
    genre: 'Pop',
    thumbnail: 'https://images.unsplash.com/photo-1493225457124-a1a2a5ee11d4?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=2JQ0k4R0f3A',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 9805,
    difficulty: 'Medium',
    difficultyInfo: { label: 'Medium', colorClass: 'bg-amber-500/10 text-amber-300 border-amber-500/20' },
    pitchMetrics: { minPitch: 55, maxPitch: 74, modePitch: 64 },
    createdAt: now,
    updatedAt: now,
    viewCount: 9805,
    playCount: 9805,
    totalPracticeTime: 0,
    maxScore: 91,
  },
  {
    id: 'song_anh_khong_doi_qua',
    title: 'Anh Không Đòi Quà',
    artist: 'Only C',
    genre: 'Khac',
    thumbnail: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=4YQ0k4Q6Q0Q',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 6400,
    difficulty: 'Easy',
    difficultyInfo: { label: 'Easy', colorClass: 'bg-emerald-500/10 text-emerald-300 border-emerald-500/20' },
    pitchMetrics: { minPitch: 51, maxPitch: 70, modePitch: 60 },
    createdAt: now,
    updatedAt: now,
    viewCount: 6400,
    playCount: 6400,
    totalPracticeTime: 0,
    maxScore: 88,
  },
  {
    id: 'song_dung_lai_o_doi_nha',
    title: 'Đừng Lại Ở Đợi Nhà',
    artist: 'The Mask',
    genre: 'Bolero',
    thumbnail: 'https://images.unsplash.com/photo-1525362081669-2b476bb628c3?w=1200&q=80',
    videoUrl: 'https://www.youtube.com/watch?v=6XQ7Q7Q7Q7Q',
    ownerId: 'seed-admin',
    status: 'public',
    plays: 15420,
    difficulty: 'Hard',
    difficultyInfo: { label: 'Hard', colorClass: 'bg-rose-500/10 text-rose-300 border-rose-500/20' },
    pitchMetrics: { minPitch: 49, maxPitch: 72, modePitch: 58 },
    createdAt: now,
    updatedAt: now,
    viewCount: 15420,
    playCount: 15420,
    totalPracticeTime: 0,
    maxScore: 95,
  },
];

const singingHistory: Array<Record<string, any>> = [];

const voiceStats = [
  { id: 'seed-admin', userId: 'seed-admin', xp: 0, level: 1, unlockedBadges: [] },
];

const userSongStats: Array<Record<string, any>> = [];

const favoriteSongs: Array<Record<string, any>> = [];

async function writeCollection(collectionName: string, docs: Array<Record<string, any>>) {
  const batch = db.batch();
  for (const entry of docs) {
    const { id, ...data } = entry;
    batch.set(db.collection(collectionName).doc(id), data, { merge: true });
  }
  await batch.commit();
}

async function main() {
  await writeCollection('users', users);
  await writeCollection('songs', songs);
  await writeCollection('singingHistory', singingHistory);
  await writeCollection('voiceStats', voiceStats);
  await writeCollection('userSongStats', userSongStats);
  await writeCollection('favoriteSongs', favoriteSongs);
  await writeCollection('leaderboardCache', [{
    id: 'global',
    rankings: voiceStats.slice().sort((a, b) => b.xp - a.xp).map((item, index) => ({
      id: item.userId,
      name: users.find((u) => u.id === item.userId)?.displayName || item.userId,
      avatar: users.find((u) => u.id === item.userId)?.photoURL || `https://api.dicebear.com/7.x/avataaars/svg?seed=${item.userId}`,
      score: item.xp,
      rank: index + 1,
    })),
    levelRankings: voiceStats.slice().sort((a, b) => b.level - a.level || b.xp - a.xp).map((item, index) => ({
      id: item.userId,
      name: users.find((u) => u.id === item.userId)?.displayName || item.userId,
      avatar: users.find((u) => u.id === item.userId)?.photoURL || `https://api.dicebear.com/7.x/avataaars/svg?seed=${item.userId}`,
      score: item.xp,
      level: item.level,
      badgesCount: item.unlockedBadges.length,
      rank: index + 1,
    })),
    lastUpdated: Date.now(),
  }]);

  console.log(`Seeded ${songs.length} songs, ${users.length} users, ${singingHistory.length} histories, ${voiceStats.length} voice stats.`);
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exitCode = 1;
});
